### ISSUE TITLE
Maximum size for font loading has been exceeded error.

### ISSUE THREAD

**Issue by izz-j** [Shirakumo/cl-fond#2]
The line:
`(defvar *font* (cl-fond:make-font #p"noto.ttf" "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ .!?" ))`
Produces the error. I have tested other fonts as well and I get the same error. Using the `:size` key does not fix this either.

**Comment by Shinmera** [comment]
Does the GL context exist and is it current in your evaluation thread?

**Comment by izz-j** [comment]
Ok I see, I did not call the function within my glfw context. I fixed that and it and resolved the error. Now I am getting an error:
`glsl 3.30 is not supported. supported versions are: 1.10, 1.20, 1.30, 1.00 es, 3.00 es, and 3.10 es`
But is a problem with glfw and unrelated to this issue.
